<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Code Couldn\'t be saved ' => '',
    'Error Processing Request ' => '',
    'Error when deleting Member Data' => '',
    'Failed to save due to error:' => '',
    'Incorrect username or password' => '',
    'Invalid voting code' => '',
    'Model wasn\'t saved!{errors}' => '',
    'Poll wasn\'t saved!{errors}' => '',
    'Row {row}: The contact with name "{name}" and email "{email}" could not be imported.' => '',
    'Row {row}: The member with name "{name}" could not be imported.' => '',
    'The requested page does not exist.' => '',
    'The selected file could not be imported.' => '',
    'The voting page has expired.<br />Please re-enter your voting code.' => '',
    'This voting code has already been used' => '',
    'Vote Couldn\'t be saved ' => '',
];
