<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Are you sure you want to delete this item?' => 'Sind sie sicher dass sie den Eintrag löschen wollen',
    'Auth Key' => '',
    'Code ID' => '',
    'Codes' => '',
    'Create' => '',
    'Create {modelClass}' => '',
    'Created At' => '',
    'Created By' => '',
    'Delete' => '',
    'Edit Members' => 'Bearbeite Mitglieder',
    'Edit {Label}' => 'Bearbeite {Label}',
    'Email' => '',
    'End Time' => '',
    'Enter Question...' => '',
    'Enter Select Max...' => '',
    'Enter Select Min...' => '',
    'Group' => '',
    'ID' => '',
    'Is Admin' => '',
    'Is Valid' => '',
    'Member ID' => '',
    'Members' => '',
    'Name' => '',
    'Option' => '',
    'Option ID' => '',
    'Organizer' => '',
    'Organizer ID' => '',
    'Organizers' => '',
    'Password Hash' => '',
    'Please enter your token' => '',
    'Please fill in your token in the form below to start voting!' => 'Bitte geben sie ihren Code in das unten stehende Feld ein um mit der Wahl zu beginnen!',
    'Please fill with an option text' => 'Bitte geben sie den Optionstext ein',
    'Please select a maximum of {count} options' => 'Bitte wählen sie maximal {count} Optionen aus',
    'Please select at least {count} options' => 'Bitte wählen sie minumum {count} Optionen aus',
    'Poll ID' => '',
    'Polls' => '',
    'Question' => '',
    'Reset' => '',
    'Search' => '',
    'Select Max' => '',
    'Select Min' => '',
    'Send Email' => 'Sende Email',
    'Start Time' => '',
    'Submit your vote' => '',
    'Title' => '',
    'Token' => '',
    'Token Input' => '',
    'Total Codes sent' => '',
    'Total Votes Received' => '',
    'Total Votes not Submitted' => '',
    'Update' => '',
    'Update your vote' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Username' => '',
    'Users' => '',
    'Vote Acceptance' => '',
    'Vote ID' => '',
    'Votes to this option' => '',
    'Votes to this option in percent' => '',
    'Votes to this option percentage to totally sent' => '',
    'Voting Code' => '',
    'ajaxtest' => '',
    'voting' => '',
    '{n, plural, =0{no Codes} =1{Code} other{Codes}}' => '',
    '{n, plural, =0{no Contacts} =1{Contact} other{Contacts}}' => '',
    '{n, plural, =0{no Members} =1{Member} other{Members}}' => '{n, plural, =0{keine Mitglieder} =1{Mitglied} other{Mitglieder}}',
    '{n, plural, =0{no Options} =1{Option} other{Options}}' => '{n, plural, =0{keine Optionen} =1{Option} other{Optionen}}',
    '{n, plural, =0{no Organizers} =1{Organizer} other{Organizers}}' => '',
    '{n, plural, =0{no Polls} =1{Poll} other{Polls}}' => '',
    '{n, plural, =0{no Users} =1{User} other{Users}}' => '',
    '{n, plural, =0{no Vote Options} =1{Vote Option} other{Vote Options}}' => '',
    '{n, plural, =0{no Votes} =1{Vote} other{Votes}}' => '',
];
