<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Row {row}: The contact with name "{name}" and email "{email}" could not be imported.' => 'Zeile {row}: Der Kontakt mit dem Namen "{name}" und Email "{email}" konnte nicht importiert werden.',
    'Row {row}: The member with name "{name}" could not be imported.' => 'Zeile {row}: Das Mitglied mit dem Namen "{name}" konnte nicht importiert werden.',
    'The requested page does not exist.' => 'Die gewünschte Seite ist nicht vorhanden.',
    'The selected file could not be imported.' => 'Die gewählte Datei kann nicht importiert werden.',
];
